name: jextract

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  jextract:
    name: OpenJDK (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-latest, windows-latest, ubuntu-latest, macos-13 ]
        include:
          - os: ubuntu-latest
            script: linux.sh
          - os: macos-latest
            script: macos.sh
          - os: macos-13
            script: macos.sh
          - os: windows-latest
            script: windows.sh

    steps:
      - uses: actions/checkout@v4

      - name: Set OS, Arch and Package
        run: jextract/gen/script/set-package.sh

      - name: Install jextract latest build
        id: setup-jextract
        uses: oracle-actions/setup-java@main
        with:
          website: jdk.java.net
          release: 'jextract'
          version: latest
          install: true

      - name: Install OpenJDK EA latest build
        id: setup-java
        uses: oracle-actions/setup-java@main
        with:
          website: jdk.java.net
          release: 'ea'
          version: latest
          install: true


      - name: Run jextract on ${{ env.RUNNER_OS }}
        run: |
          java -version
          jextract --version
          jextract/gen/script/${{ matrix.script }}

      - name: Checkin the generated source
        uses: stefanzweifel/git-auto-commit-action@v4

          
       
